compile_job:
    stage: compile
    script:
        - apt update -y
        - apt install mvn -y
        - cd /path/to/pom.xml
        - mvn compile
    only:
        refs:
            - master
 
 build_job:
    stage: build
    script:
        - mvn package
    only:
        refs:
            - master
